// Date: 9/15/2014 6:16:19 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.professorvennie.machinerycraft.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCampFire extends ModelBase {
    //fields
    ModelRenderer Base;
    ModelRenderer Log1;
    ModelRenderer Log2;
    ModelRenderer Log3;
    ModelRenderer Log4;
    ModelRenderer Log5;
    ModelRenderer Log6;
    ModelRenderer Log7;
    ModelRenderer Log8;
    ModelRenderer Log9;
    ModelRenderer Log10;

    public ModelCampFire() {
        textureWidth = 64;
        textureHeight = 32;

        Base = new ModelRenderer(this, 0, 0);
        Base.addBox(0F, 0F, 0F, 5, 1, 5);
        Base.setRotationPoint(-3F, 23F, -2F);
        Base.setTextureSize(64, 32);
        Base.mirror = true;
        setRotation(Base, 0F, 0F, 0F);
        Log1 = new ModelRenderer(this, 0, 0);
        Log1.addBox(0F, 0F, 0F, 1, 9, 1);
        Log1.setRotationPoint(-2F, 16F, 0F);
        Log1.setTextureSize(64, 32);
        Log1.mirror = true;
        setRotation(Log1, 0F, 0F, 0.4712389F);
        Log2 = new ModelRenderer(this, 0, 0);
        Log2.addBox(0F, 0F, 0F, 1, 9, 1);
        Log2.setRotationPoint(-1F, 16F, 2F);
        Log2.setTextureSize(64, 32);
        Log2.mirror = true;
        setRotation(Log2, 0F, 1.570796F, 0.4712389F);
        Log3 = new ModelRenderer(this, 0, 0);
        Log3.addBox(0F, 0F, 0F, 1, 9, 1);
        Log3.setRotationPoint(1F, 16F, 1F);
        Log3.setTextureSize(64, 32);
        Log3.mirror = true;
        setRotation(Log3, 0F, 3.141593F, 0.4712389F);
        Log4 = new ModelRenderer(this, 0, 0);
        Log4.addBox(0F, 0F, 0F, 1, 9, 1);
        Log4.setRotationPoint(0F, 16F, -1F);
        Log4.setTextureSize(64, 32);
        Log4.mirror = true;
        setRotation(Log4, 0F, 4.712389F, 0.4712389F);
        Log5 = new ModelRenderer(this, 0, 0);
        Log5.addBox(0F, 0F, 0F, 7, 1, 1);
        Log5.setRotationPoint(-4F, 22F, 2F);
        Log5.setTextureSize(64, 32);
        Log5.mirror = true;
        setRotation(Log5, 0F, 0F, 0F);
        Log6 = new ModelRenderer(this, 0, 0);
        Log6.addBox(0F, 0F, 0F, 7, 1, 1);
        Log6.setRotationPoint(-4F, 22F, -2F);
        Log6.setTextureSize(64, 32);
        Log6.mirror = true;
        setRotation(Log6, 0F, 0F, 0F);
        Log7 = new ModelRenderer(this, 0, 0);
        Log7.addBox(0F, 0F, 0F, 1, 1, 7);
        Log7.setRotationPoint(1F, 21F, -3F);
        Log7.setTextureSize(64, 32);
        Log7.mirror = true;
        setRotation(Log7, 0F, 0F, 0F);
        Log8 = new ModelRenderer(this, 0, 0);
        Log8.addBox(0F, 0F, 0F, 1, 1, 7);
        Log8.setRotationPoint(-3F, 21F, -3F);
        Log8.setTextureSize(64, 32);
        Log8.mirror = true;
        setRotation(Log8, 0F, 0F, 0F);
        Log9 = new ModelRenderer(this, 0, 0);
        Log9.addBox(0F, 0F, 0F, 7, 1, 1);
        Log9.setRotationPoint(-4F, 20F, -2F);
        Log9.setTextureSize(64, 32);
        Log9.mirror = true;
        setRotation(Log9, 0F, 0F, 0F);
        Log10 = new ModelRenderer(this, 0, 0);
        Log10.addBox(0F, 0F, 0F, 7, 1, 1);
        Log10.setRotationPoint(-4F, 20F, 2F);
        Log10.setTextureSize(64, 32);
        Log10.mirror = true;
        setRotation(Log10, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Base.render(f5);
        Log1.render(f5);
        Log2.render(f5);
        Log3.render(f5);
        Log4.render(f5);
        Log5.render(f5);
        Log6.render(f5);
        Log7.render(f5);
        Log8.render(f5);
        Log9.render(f5);
        Log10.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}
